### ISSUE TITLE
graphql-schema missing type

### ISSUE THREAD

**Issue by spillz-dxb** [nileio/node-red-contrib-graphql-server#12]
I would like to report an error in both the example flows , showing graphql-schema missing unrecognised type
![graphql serrver missing schema-1](https://user-images.githubusercontent.com/5900390/114309394-00bec000-9af8-11eb-8f7f-cd5258d8e12c.png)

In the Graphql in node , i am unable to create or add schemas . Also noted on loading the editor ( refresh) fails to load the editor .
Need to then uninstall the server and restart flow .This may be due to the missing type.

Also would appreciate a client flow to test the server

Great work nileio , indeed good for noobs to learn GraphQL

**Comment by nileio** [comment]
@spillz-dxb this is very odd !
Do you have node-red 1.3 installed ? the node depends on the latest version of node-red. Please upgrade node-red and ensure you have node-red 1.3 or above
also nodejs version should be 11.15 or above

can you go to ~/.node-red and run `npm install node-red-contrib-graphql-server --engine-strict` ?

apparently the installation of the node was not successfull for some reason and it didnt install the node properly.
Can you show a screenshot of the Pallette Manager when you try to install. there is a button which shows all the nodes within the package, and it should include graphql-schema node
also you dont need to uninstall the server if something like that happen , you can run node-red in safe mode and it will load up and enable you to fix your flow

**Comment by spillz-dxb** [comment]
Hi,
    I figured out that the issue was my version of NR was 1.2.9 , an upgrade to 1.3.1 ,resolved it completely.
In the previous case the node was installed in the pallette manager and was available in the pallete to drag and drop , but the graphql-schema wasnt registering and remained unknown in the configuration nodes .Upon a refresh the nodes and flows dont load any more , neither were there any errors in the console .
This was happening on installs from pallette manager and cli . 
Now with 1.3.1 im able to use the graphql voyager after additions in the settings.js

Thanks any ways , just laying it down here for others
