### ISSUE TITLE
Not Installed Properly

### ISSUE THREAD

**Issue by spillz-dxb** [nileio/node-red-contrib-graphql-server#17]
Have been using the server for older versions of Node.js and Node-red .On installing on a newer version as below.

25 Mar 12:32:10 - [info] Node-RED version: v2.2.1
25 Mar 12:32:10 - [info] Node.js  version: v17.6.0
25 Mar 12:32:10 - [info] Linux 5.4.0-100-generic x64 LE

Installation throws some warning and on running  NR  ,get the following errors.
On importing flows , missing type graphql-in is shown.

Mar 12:32:16 - [warn] [node-red-contrib-graphql-server/graphql-in] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './public/extractFiles' is not defined by "exports" in /home/user/.node-red/node_modules/extract-files/package.json
25 Mar 12:32:16 - [warn] [node-red-contrib-graphql-server/graphql-subscriptionserver] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './public/extractFiles' is not defined by "exports" in /home/user/.node-red/node_modules/extract-files/package.json

Any ways to resolve this without downgrading?.Thanks in advance.

**Comment by nileio** [comment]
hi @spillz-dxb can you share the installation log messages ? Did you install it from the Menu - Manage palette ?
