### ISSUE TITLE
How to enable visual editor and voyager?

### ISSUE THREAD

**Issue by plato79** [nileio/node-red-contrib-graphql-server#18]
I pasted these lines at the end of settings.js:
```js
graphqlSchema: {
  editor: true
}
graphqlIn: {
  voyager: true
}
```
which didn't change anything. It still gives the same message. 

I tried to put them in `module.exports = { }` section but this time I got an error. How can I enable these tools?

I saw another issue which mentions removing these tools altogether. Is this already done?

**Comment by nileio** [comment]
Hey @plato79 , the tools are still there.
enabling them is simple in `settings.js` which is usually in `~/.node-red` folder file add the following then restart node-red. make sure your file is valid , that is those settings should be part of the setttings ! not after the end of the file!
  ```
{
... some default settings are here
,
graphqlSchema: {
    editor: true,
  },
  graphqlIn: {
    voyager: true,
  },
.... other settings might also go here
}
```

attach a screen shot if you still face issues

**Comment by nileio** [comment]
Hi @plato79 can I close this ?
