### ISSUE TITLE
add simple examples and schema

### ISSUE THREAD

**Issue by nileio** [nileio/node-red-contrib-graphql-server#7]

**Comment by limengsong** [comment]
@nileio 
data files
 How is chinook.sqlite generated?
Will the program write it automatically?
Or is it written manually in advance?

**Comment by nileio** [comment]
@limengsong chinook.sqlite is a sqlite database https://github.com/lerocha/chinook-database included with the node as an example. It is inside the examples folder ! I also included a GraphQL schema based on the database.
update to the latest node version, then import the example where you will have a note explaining what to do, sample queries, and how to point your sqlite node to the database file location

**Comment by nileio** [comment]
added new example flow for starwars schema using swapi data
